#!/usr/bin/env python3
"""Render compliance/control-matrix.md from compliance/controls.yaml.

  python scripts/gen_control_matrix.py          # write the matrix
  python scripts/gen_control_matrix.py --check  # CI: fail if the committed matrix is stale
                                                #     or a control points at a missing file
"""
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "compliance" / "controls.yaml"
OUT = ROOT / "compliance" / "control-matrix.md"
FW = [("nist_csf", "NIST CSF 2.0"), ("iso27001", "ISO 27001:2022"), ("soc2", "SOC 2"),
      ("sox_itgc", "SOX ITGC"), ("gdpr", "GDPR")]


def render(doc: dict) -> str:
    lines = [
        "# Control matrix",
        "",
        "<!-- Generated by scripts/gen_control_matrix.py from compliance/controls.yaml. Do not edit by hand. -->",
        "",
        f"Owner: {doc['owner']}",
        "",
        "| ID | Control | " + " | ".join(n for _, n in FW) + " | Automated checks | Frequency |",
        "|---|---|" + "---|" * len(FW) + "---|---|",
    ]
    for c in doc["controls"]:
        fws = [", ".join(c["frameworks"].get(k) or []) or "—" for k, _ in FW]
        lines.append(f"| {c['id']} | **{c['name']}** | " + " | ".join(fws) +
                     f" | {'; '.join(c['automated_checks'])} | {c['frequency']} |")
    lines += ["", "## Control details", ""]
    for c in doc["controls"]:
        lines += [
            f"### {c['id']} · {c['name']}",
            "",
            c["description"],
            "",
            "- **Implemented in:** " + ", ".join(f"`{p}`" for p in c["implementation"]),
            "- **Evidence:** " + "; ".join(c["evidence"]),
            "- **Vanta:** " + c["vanta"]["monitors"],
            "",
        ]
    counts = {n: len({x for c in doc["controls"] for x in (c["frameworks"].get(k) or [])}) for k, n in FW}
    lines += ["## Coverage", "", "| Framework | Distinct references |", "|---|---|"]
    lines += [f"| {n} | {v} |" for n, v in counts.items()]
    return "\n".join(lines) + "\n"


def main() -> int:
    doc = yaml.safe_load(SRC.read_text(encoding="utf-8"))
    missing = [f"{c['id']}: {p}" for c in doc["controls"] for p in c["implementation"]
               if not (ROOT / p).exists()]
    if missing:
        print("Controls reference missing files:\n  " + "\n  ".join(missing))
        return 1
    text = render(doc)
    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != text:
            print("compliance/control-matrix.md is stale: run python scripts/gen_control_matrix.py")
            return 1
        print(f"Control matrix up to date ({len(doc['controls'])} controls).")
        return 0
    OUT.write_text(text, encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)} ({len(doc['controls'])} controls)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
